### ISSUE TITLE
Unable to add tasks using iOS 7 on iPhone 5

### ISSUE THREAD

**Issue by stevethinkdata** [todotxt/todo.txt-ios#187] opened 2013-09-19 19:23 UTC
I upgraded to iOS 7 yesterday and tried using ToDoTXT as I do every day - it appears that entering tasks doesn't work anymore.  I'm unable to see the text as I type it on the Add Tasks screen.  I did try uninstalling/reinstalling ToDoTXT after iOS 7 was upgraded but the problem still exists and at the moment I'm unable to use ToDoTXT for anything other than viewing tasks I have already entered.

**Comment by dmd** [comment] 2013-09-19 20:40
Same here. Typing doesn't show up on the screen.

**Comment by portenkirchner** [comment] 2013-09-20 15:16
When adding a new task, the text moves up behind the top bar. Still can write and save the task, but can't see the text while typing. (On an iPhone 4)

**Comment by nizmogtr** [comment] 2013-09-22 05:18
same here

**Comment by gregwschroeder** [comment] 2013-09-23 14:14
Gina, thanks for the new update to 1.5 that includes the ability to add dates to entries. I generally use todo.txt on the windows desktop with Ben Hughes todotxt.net application, but have refrained until this update with the add dates option. But as mentioned, I'm experiencing the same issue with both new and editing tasks moving up behind the top bar, and cannot see the text while typing. I just updated to iOS 7 and have the 4S. Thanks again and looking forward to the fix for this.

**Comment by ginatrapani** [comment] 2013-09-23 21:15
Confirmed that this is indeed a bug. It looks like the typing is going on behind the top bar. We're on it, thanks and sorry all.

**Comment by ginatrapani** [comment] 2013-09-24 14:57
Fixed in #190. Submitting to Apple for approval today!

**Closed as completed by ginatrapani** 2013-09-24 14:57 UTC

**Comment by dmd** [comment] 2013-09-24 15:24
Gina, will this also fix the associated crashes? If not, would crash reporter logs help?

**Comment by ginatrapani** [comment] 2013-09-24 15:34
I don't think so. Crash reporter logs would definitely help!

On Tue, Sep 24, 2013 at 8:24 AM, Daniel M. Drucker <notifications@github.com

> wrote:
> 
> Gina, will this also fix the associated crashes? If not, would crash
> reporter logs help?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ginatrapani/todo.txt-ios/issues/187#issuecomment-25014657
> .

## 

http://ginatrapani.org

**Comment by dmd** [comment] 2013-09-24 15:50
All right. Will send tonight when I have access to my home machine.

**Comment by dmd** [comment] 2013-09-24 15:52
Here's one of them: http://ix.io/8e8

**Comment by ginatrapani** [comment] 2013-09-24 16:00
Thanks @dmd . Can I ask a favor? Can you open a new ticket for the crashiness (this one is closed) and describe the exact behavior, and include the device and iOS version you're running and this link to your crash logs?
