### ISSUE TITLE
Add line number and align priority with task text on individual task screen

### ISSUE THREAD

**Issue by ginatrapani** [todotxt/todo.txt-ios#51] opened 2011-10-30 00:22 UTC
The individual task screen task format should be consistent with the list view. Specifically,  on the individual task screen:

If "Show Line numbers" is enabled in settings, the line number should display in the same exact place it does in the list view.

Priority should be aligned with the first line of task text as well (right now it's centered vertically).

**Comment by ginatrapani** [comment] 2011-12-06 20:19
Hey @rhussmann, is there any chance you might have time to take a stab at this in the next week or so? I only ask b/c you did such good work formatting the list view. If not, no big deal, just wanted to try. :)

So you know, @chuckbjones and I are doing an iOS push to App Store submission in the next couple of weeks. I've prioritized issues into milestones - 1.0 critical path, 1.0 would be nice, and 2.0, if you're interested in seeing what's where. 

We've only got 2 more items left on the 1.0 critical path list--this one, and the Dropbox API deprecated method, which @chuckbjones is looking at.

**Comment by rhussmann** [comment] 2011-12-06 20:23
I've been meaning to attack a few more of these tasks, but between Thanksgiving and the end of the semester I've gotten kinda bogged-down with other work. At any rate, I should have time to take a crack at this within the week.

**Comment by rhussmann** [comment] 2011-12-06 20:23
In other words, I'll take this one.

**Comment by ginatrapani** [comment] 2011-12-06 20:25
Great news, thanks!!

**Comment by paulroub** [comment] 2011-12-09 03:40
Missed that this was in progress... I took a stab at the priority-alignment portion (learning iOS development, so baby steps...) 

Got that straightened out, as well as resizing the description text when we rotate.  I haven't touched line numbers in that view.

The commit is at paulroub@ 5907c201ae1913a3d19e1369937994ecabcbe132 - I'll send a pull request, but ignore it if it's redundant.

**Comment by paulroub** [comment] 2011-12-09 04:39
Added a line numbers swag to the pull request.

**Comment by ginatrapani** [comment] 2011-12-09 23:33
Hey @paulroub thanks, this is almost there. There seems to be a really big space between the priority and the task though. Check out what it looks like:

![Big space](https://img.skitch.com/20111210-dd2rtcb6h7b55yisaaxxu9wt11.png)

Compared to list view:

![List view](https://img.skitch.com/20111210-j55xfeswpnc6ujp1x4ghawyf3r.png)

Could we nudge those two a bit closer?

**Comment by ginatrapani** [comment] 2011-12-09 23:34
Looking at those two images, I'm realizing we want contexts/projects to be slightly grayed out as well on the individual task screen, same as they are in list view.

**Comment by paulroub** [comment] 2011-12-09 23:39
Ha. That was being calculated, but forgot to actually _set_ the new position on the label. Just pushed the fix.

**Comment by ginatrapani** [comment] 2011-12-10 00:51
Better! Now we just have to align the date:

![](https://img.skitch.com/20111210-muxfurnp9t8t28amyt271ssau3.png)

**Comment by ginatrapani** [comment] 2011-12-10 00:54
Here's the commit where projects/contexts get grayed 872c67504b3be01112d20f8ef7a733233483308d

**Comment by paulroub** [comment] 2011-12-10 04:59
The date alignment was pushed earlier, but I'm learning that there's so much I don't know about the interaction between UIKit views and the Core Text methods used to draw the attributed strings (for context/project graying purposes).  In particular, why said strings seem to want to draw themselves relative to the cell's container, not the cell itself.  If someone more iOS-conversant were to take a look at that part, they'd likely beat me to the solution.

**Comment by rhussmann** [comment] 2011-12-10 23:03
Hey @paulroub , I'll try to take a peek at this soon. The issue is with grouped tableview cells. If you look at the frame for the cell, or it's content view, it's difficult (perhaps impossible, programmatically?) to determine the margin between the edge of the screen and the rounded rect of the cell. I could be wrong, but I believe this was the issue when I first looked at this feature.

I wrote the attributed text-string stuff, so if you have any questions I'd be happy to try and answer them. I'm no CoreText wizard by any stretch, but if I can help you solve the problem, I'd be happy to help out.

**Comment by paulroub** [comment] 2011-12-10 23:35
Thanks @rhussmann - that was enough to get me looking at it again, after some sleep and a day outside :-)

I was adding the attributed label as a subview of the cell, not a subview of the cell's `contentView`.  Fixed that, and things are much better.  Added to the pull request.

**Comment by ginatrapani** [comment] 2011-12-11 01:41
This looks fantastic! Merging now. Congrats on your first commit to the project, @paulroub, and thanks for your time and effort.

**Closed as completed** 2011-12-11 01:44 UTC
Labels: usability
