### ISSUE TITLE
Delete operation leaves blank line in todo.txt file

### ISSUE THREAD

**Issue by jperkel** [todotxt/todo.txt-ios#46] opened 2011-10-29 17:24 UTC
When deleting a task, the app leaves a blank line in the todo.txt file, which at least on my system (iPhone 5.0 simulator)  is rendered as an "empty" task (ie, numbered but blank)

**Comment by chuckbjones** [comment] 2011-11-12 08:56
I can't reproduce this. @jperkel, are there any specific steps to make this happen?

**Comment by ginatrapani** [comment] 2011-11-15 02:38
I'm unable to reproduce this as well. Closing issue unless/until we get specific repro steps.

**Closed as completed by ginatrapani** 2011-11-15 02:38 UTC
Labels: bug

**Comment by jperkel** [comment] 2011-11-15 04:07
Hi, all,
Sorry for the long absence, I've been buried. For some reason, I can't reproduce it either. Maybe it was some weirdness from early on ... when I use the program now, it doesn't happen.

That said, I do have a blank line in my todo.txt file, which renders in my iOS simulation as a blank entry in the list. Is that supposed to happen?

Thanks all!
Jeff
